export const frcConfig = {
  title: "Endeudamiento máximo x FRC",
  subTitle: "Score de riesgo",
  totalScoreLabel: "Puntaje total",
  totalScoreMax: "/1000",
  seniorityLabel: "Antigüedad",
  seniorityMax: "/200",
  centralRiskLabel: "Central de riesgo",
  centralRiskMax: "/200",
  employmentStabilityLabel: "Índice de estabilidad laboral",
  employmentStabilityMax: "/300",
  maritalStatusLabel: "Estado civil - Casado",
  maritalStatusMax: "/50",
  economicActivityLabel: "Actividad economica - Pensionado",
  economicActivityMax: "/200",
  incomesLabel: "(+) Ingresos mensuales",
  timesIncome: "(x) No. de veces el ingreso para este score",
  maxIndebtedness: "Endeudamiento máximo",
  closeBtn: "Cerrar",
  loading: "Cargando...",
  intercept: "Intercepto",
  maxLimit: "(=) Tope máximo",
  totalPortafolio: "(-) Cartera total vigente",
  scoreLabel: "749",
  loremIpsum:
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
  error: {
    title: "Error cargando datos",
    message:
      "No se pudieron cargar los datos. Por favor, intente nuevamente más tarde.",
  },
};
