export const DataCapacityAnalysis = {
  modalTitle: "Análisis de capacidad de pago",
  closeButton: "Cerrar",
  workRents: "Rentas de trabajo",
  capitalIncome: "Rentas de capital",
  professionalServices: "Servicios profesionales independientes",
  businessVentures: "Emprendimientos o micronegocios",
  concept: "Concepto",
  availableValue: "Valor disponible",
  periodicSalary: "(+) Salario periódico",
  otherNonSalaryEmoluments: "(+) Otros emolumentos no salariales",
  pensionPayments: "(+) Mesadas pensionales",
  professionalFees: "(+) Honorarios profesionales",
  rentals: "(+) Arrendamientos",
  dividends: "(+) Dividendos",
  financialReturns: "(+) Rendimientos financieros",
  businessUtilities: "(+) Utilidades de negocios personales",
  totalIncome: "(=) Valor total de los ingresos",
  minimumPaymentReserve: "(-) Reserva del pago mínimo ({percent}%)",
  currentObligations: "(-) Obligaciones vigentes",
  paymentCapacity: "(=) Capacidad de pago",
};
