export const ModalConfig = {
  closeButton: "Cerrar",
  code: "Número de obligación",
  terminated: "Próximo vencimiento",
  selectedText: "Obligaciones seleccionadas:",
  newObligations: "Nuevas obligaciones encontradas:",
  creditInvestment: "Crédito libre inversión",
  close: "Cerrar",
  keep: "Guardar",
  edit: "Editar obligaciones",
  collectedValue: "Valor total recogido.",
  title: "Obligaciones recogidas",
  loading: "Cargando...",
  noSelected: "No hay obligaciones seleccionadas.",
};
